I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Not a displayable: <Character: u'girl'>

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/enikfeirgraw/assets.rpyc", line 9, in script
  File "/usr/share/renpy/renpy/ast.py", line 911, in execute
    renpy.exports.image(self.imgname, img)
  File "/usr/share/renpy/renpy/exports.py", line 347, in image
    d = renpy.easy.displayable(d)
  File "/usr/share/renpy/renpy/easy.py", line 108, in displayable
    raise Exception("Not a displayable: %r" % (d,))
Exception: Not a displayable: <Character: u'girl'>

Linux-3.8.11-x86_64-with-debian-jessie-sid
Ren'Py 6.99.12.2.2029
WIP 1.0
